insert into Student (email, name, PASSWORD, studDetails) values ('hluckham0@google.ru', 'Hazel Luckham', 'X1uZcoIh0dj',1);
insert into Student (email, name, password, studDetails) values ('sbowden1@yellowbook.com', 'Sonnnie Bowden', 'SJc4aWSU',2);
insert into Student (email, name, password, studDetails) values ('qllorens2@howstuffworks.com', 'Quillan Llorens', 'W6rJuxd',3);
insert into Student (email, name, password, studDetails) values ('cstartin3@flickr.com', 'Clem Startin', 'XYHzJ1S',4);
insert into Student (email, name, password) values ('tattwool4@biglobe.ne.jp', 'Thornie Attwool', 'Hjt0SoVmuBz');
insert into Student (email, name, password) values ('hguerre5@deviantart.com', 'Harcourt Guerre', 'OzcxzD1PGs');
insert into Student (email, name, password) values ('htaffley6@columbia.edu', 'Holmes Taffley', 'xowtOQ');
insert into Student (email, name, password) values ('aiannitti7@is.gd', 'Alexandra Iannitti', 'TWP4hf5j');
insert into Student (email, name, password) values ('ljiroudek8@sitemeter.com', 'Laryssa Jiroudek', 'bXRoLUP');
insert into Student (email, name, password) values ('cjaulme9@bing.com', 'Cahra Jaulme', 'FnVklVgC6r6');
